# Generated by Django 5.0.4 on 2024-04-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Bill_app",
        ),
    ]
